# ----- Services exposed to the outside world ------
# solr web server
kind: Service
apiVersion: v1
metadata:
  name: rabbitmqtcp
  namespace: fabricrealtime
  labels:
    expose: external
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5671
    targetPort: 5671
    protocol: TCP
    name: tcp
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: ssl
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: mgmt
---
