apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: realtime.ingress.interfaceengine
  namespace: fabricrealtime
  labels:
    expose: external
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - http:
      paths:
      - path: /mirth
        backend:
          serviceName: interfaceenginepublic
          servicePort: 80
