apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: realtime.ingress.rabbitmq
  namespace: fabricrealtime
  labels:
    expose: external
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
      # kubernetes.io/ingress.class: traefik
      # ingress.kubernetes.io/ssl-passthrough: "true"
      # change /certificates to /
      # https://docs.giantswarm.io/guides/advanced-ingress-configuration/
      # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
      # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
      # ingress.kubernetes.io/rewrite-target: /
      # ingress.kubernetes.io/add-base-url: "true"
      # https://docs.traefik.io/configuration/backends/kubernetes/
      # traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /rabbitmq
        backend:
          serviceName: rabbitmqpublic
          servicePort: 80
