kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: certificateserver
# namespace for this pod
  namespace: fabricrealtime
  labels:
    app: certificateserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate
  selector:
    matchLabels:
      app: certificateserver
  template:
    metadata:
      labels:
        app: certificateserver
    spec:
      containers:
        - name: certificateserver
          image: {{ .Values.images.certificateserver }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: certserver
          volumeMounts:
            - name: fabric-ssl-download-volume
              mountPath: /opt/certs/client/
      volumes:
      - name: fabric-ssl-download-volume
        secret:
          secretName: fabric-ssl-download-cert
